{
    "name": "with-error",
    "version": "0.1.4",
    "description": "Exception as function",
    "main": "index.js",
    "scripts": {
        "test": "tsc && tslint --project tsconfig.json && jest --verbose --coverage",
        "watch:test": "jest --watch --coverage --verbose"
    },
    "repository": {
        "type": "git",
        "url": "git+https://github.com/arvitaly/with-error.git"
    },
    "keywords": [],
    "author": "",
    "license": "ISC",
    "bugs": {
        "url": "https://github.com/arvitaly/with-error/issues"
    },
    "homepage": "https://github.com/arvitaly/with-error#readme",
    "jest": {
        "testMatch": [
            "**/__tests__/**/*.js",
            "**/?(*.)+(spec|test).js"
        ]
    },
    "devDependencies": {
        "@types/jest": "^25.2.1",
        "coveralls": "^3.0.11",
        "jest": "^25.3.0",
        "tslint": "^6.1.1",
        "typescript": "^3.8.3"
    }
}
