{
    "name": "with-error",
    "version": "0.1.2",
    "description": "Exception as function",
    "main": "index.js",
    "scripts": {
        "test": "tsc && tslint --project tsconfig.json && jest --verbose --coverage",
        "watch:test": "jest --watch --coverage --verbose"
    },
    "repository": {
        "type": "git",
        "url": "git+https://github.com/arvitaly/with-error.git"
    },
    "keywords": [],
    "author": "",
    "license": "ISC",
    "bugs": {
        "url": "https://github.com/arvitaly/with-error/issues"
    },
    "homepage": "https://github.com/arvitaly/with-error#readme",
    "jest": {},
    "devDependencies": {
        "@types/jest": "^23.1.3",
        "coveralls": "^3.0.2",
        "jest": "^23.2.0",
        "tslint": "^5.10.0",
        "typescript": "^2.9.2"
    }
}
